# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_quote', to='main_app.User'),
        ),
        migrations.AddField(
            model_name='quote',
            name='uploaded_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_quote', to='main_app.User'),
            preserve_default=False,
        ),
    ]
